site_name: Initial v2 Platform
site_author: SKT 주재현
site_description: Initial v2 Platform
site_url: https://initial-v2-platform.readthedocs.io/ko/latest/
google_analytics: ['UA-171779938-1', 'https://initial-v2-platform.readthedocs.io/ko/latest/']

repo_name: source repository
repo_url: https://github.com/sktston/initial-v2-platform-doc

site_name: Initial v2 Platform
nav:
  - Introduction : index.md
  - Release note: release_note.md
  - Agency : agency.md
  - JAVA SDK API: java_api/java_api.md



plugins:
  - search
markdown_extensions:
  - meta
  - toc:
      permalink: true
      baselevel: 1
  - admonition
  - footnotes

theme:
  name: readthedocs
  highlightjs: true

extra:
  version: 0.1