site_author: SKT 주재현
site_description: Initial Platform
site_url: https://initial-v2-platform.readthedocs.io/
google_analytics: ['UA-171779938-1', 'https://initial-v2-platform.readthedocs.io/']

repo_url: https://github.com/sktston/initial-v2-platform-doc

site_name: Initial Platform
nav:
  - 'Initial Platform' :
      - 'Introduction' : 'index.md'
      - 'Terms' : 'terms.md'
      - 'Services': 'services.md'
      - 'Release notes' : 'release_note.md'
#  - 'Mobile Agency Service' :
#      - 'Initial Agency' : 'agency.md'
#      - 'Agency Protocols' : 'agency_protocol.md'
  - 'Web Console Service' :
      - 'Web Console 소개' : 'web_console.md'
      - 'Web Console 이용방법' : 'web_console_signup.md'
  - 'Cloud Agent API Referece':
      - 'Open API list': 'open_api_list.md'
#      - 'Wallet & DID' : 'open_api_wallet.md'
      - 'Auto Connection': 'open_api_auto_connection.md'
#      - 'Manual Connection': 'open_api_manual_connection.md'
#      - 'Router Connection': 'open_api_router_connection.md'
      - 'Create Schema & CredDef': 'open_api_schema_creddef.md'
      - 'Auto Credential Issue': 'open_api_auto_credential.md'
#      - 'Manual Credential Issue': 'm_credential.md'
      - 'Proof Presentation': 'open_api_proof.md'
      - 'Revocation': 'open_api_revocation.md'
#      - 'Message': 'message.md'
  - 'Demo samples' :
#      - 'DID VCX Java Demo' : 'demo.md'
#      - 'DID VCX NodeJS Demo': 'node_demo.md'
      - 'Cloud Agent REST API Demo' : 'cloud_agent_demo.md'
#  - 'SDK API' :
#      - 'Java APIs' : 'java_api/java_api.md'
#      - 'iOS APIs' : 'ios_api/ios_api.md'
  - 'Blockchain Node' :
      - 'Blockchain Network' : 'blockchain.md'


plugins:
  - search
markdown_extensions:
  - meta
  - toc:
      permalink: true
      baselevel: 1
  - admonition
  - footnotes

theme:
  name: readthedocs
  nav_style: light
  navigation_depth : 2
  highlightjs : true
  hljs_style : github

extra:
  version: 1.0.3