site_name: Initial v2 Platform
site_author: SKT 주재현
site_description: Initial v2 Platform
site_url: https://initial-v2-platform.readthedocs.io/
google_analytics: ['UA-171779938-1', 'https://initial-v2-platform.readthedocs.io/']

repo_url: https://github.com/sktston/initial-v2-platform-doc

site_name: Initial Platform
nav:
  - 'Initial Platform' :
      - 'Introduction' : 'index.md'
      - 'Services' : 'services.md'
      - 'Terms' : 'terms.md'
      - 'Release notes' : 'release_note.md'
  - 'Agency' :
      - 'Initial Agency' : 'agency.md'
      - 'Protocols' : 'agency_protocol.md'
  - 'Web Console' :
      - 'Agent APIs admin site' : 'api.md'
      - 'API list': 'api_list.md'
      - 'API Example':
        - 'Auto Connection': 'auto_connection.md'
        - 'Manual Connection': 'manual_connection.md'
        - 'Schema & CredDef': 'schema_creddef.md'
        - 'Credential': 'credential.md'
  - 'Demo/Reference' :
      - 'DID VCX Java Demo' : 'demo.md'
      - 'DID VCX NodeJS Demo': 'node_demo.md'
      - 'Cloud Agent REST API Demo' : 'cloud_agent_demo.md'
  - 'SDK API' :
      - 'Java APIs' : 'java_api/java_api.md'
      - 'iOS APIs' : 'ios_api/ios_api.md'



plugins:
  - search
markdown_extensions:
  - meta
  - toc:
      permalink: true
      baselevel: 1
  - admonition
  - footnotes

theme:
  name: readthedocs
  nav_style: light
  navigation_depth : 2
  highlightjs : true
  hljs_style : github

extra:
  version: 0.2