site_name: Initial v2 Platform
site_author: SKT 주재현
site_description: Initial v2 Platform
site_url: https://initial-v2-platform.readthedocs.io/
google_analytics: ['UA-171779938-1', 'https://initial-v2-platform.readthedocs.io/']

repo_url: https://github.com/sktston/initial-v2-platform-doc

site_name: Initial Platform
nav:
  - 'Initial Platform' :
      - 'Introduction' : 'index.md'
      - 'Services' : 'services.md'
      - 'Terms' : 'terms.md'
      - 'Release notes' : 'release_note.md'
  - 'Agency' :
      - 'Initial Agency' : 'agency.md'
      - 'Protocols' : 'agency_protocol.md'
  - 'Web Console' :
      - 'Agent APIs admin site' : 'api.md'
      - 'API Doc': 'api_doc.md'
  - Reference :
      - 'DID Demo' : 'demo.md'
  - SDK API :
      - 'Java APIs' : 'java_api/java_api.md'
      - 'iOS APIs' : 'ios_api/ios_api.md'



plugins:
  - search
markdown_extensions:
  - meta
  - toc:
      permalink: true
      baselevel: 1
  - admonition
  - footnotes

theme:
  name: readthedocs
  nav_style: dark
  navigation_depth : 2
  highlightjs : true
  hljs_style : github
  extra_css : theme_extra.css


extra:
  version: 0.2