site_name: Initial v2 Platform
site_author: SKT 주재현
site_description: Initial v2 Platform
site_url: https://initial-and-adt.readthedocs.io/ko/latest/
copyright:
google_analytics: ['UA-163860122-1', 'https://initial-and-adt.readthedocs.io/ko/latest/']

repo_name: source repository
repo_url: https://github.com/sktston/initial-v2-platform-doc

nav:
  - Introduction:
      - 'Overview': ''
      - 'Understanding SDK': ''
      - 'Release note': ''
  - Initial v2 APIs:
      - 'Init/Common API': ''
      - 'Credential API': ''
      - 'Connection API': ''
  - About: about.md
  - Tutorial : initial_server_demo.md


plugins:
  - search
markdown_extensions:
  - meta
  - toc:
      permalink: true
      baselevel: 1
  - admonition
  - footnotes

theme:
  name: readthedocs
  highlightjs: true

extra:
  version: 0.1
